name: Snyk test on PR commits

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-8-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >-
            --all-projects
            --configuration-matching='^runtimeClasspath$'
            --fail-on=upgradable
            --severity-threshold=high
            --policy-path=.snyk
            --org=radar-base
